using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Data;
using System.ComponentModel;
using Expression.Blend.SampleData.SampleDataSource;

namespace AutoFilterDataGridTest
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window, INotifyPropertyChanged
    {
        private DataTable testTable;
        public DataTable TestTable
        {
            get
            {
                return testTable;
            }
        }
        public MainWindow()
        {
            testTable = new DataTable();
            testTable.Columns.Add("Property1");
            testTable.Columns.Add("Property2");
            SampleDataSource testData = new SampleDataSource();
            foreach(Item test in testData.Collection)
            {
                testTable.LoadDataRow(new object[] { test.Property1, test.Property2 }, true);
            }
            InitializeComponent();
        }

        public event PropertyChangedEventHandler PropertyChanged;

        private void AutoFilterDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }
    }
}
